

title: Hikmah Ideas
author: Shehu Ibrahim Muhammad
email: profshehu94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is the new springs of ideas i hVE.

# social links
twitter_username: @shehu_hikmah
github_username:  hikmah94

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
